name: xtream-challenge1
channels:
  - defaults
dependencies:
  - numpy=1.24.3
  - python=3.11.5
  - pandas
  - ipykernel
  - numba=0.58.1
  - conda-forge::ydata-profiling
  - scikit-learn
  - ipywidgets
