name: Train

on:
  push:
    branches:
      #- master
      - test
    paths:
      - 'datasets/diamonds/*.csv'

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: 3.11.5
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
 
    - name: Run training task
      run: |
        python src/steps/train.py
