name: Train

on:
  push:
    branches:
      - main

    paths:
      - 'datasets/diamonds/*.csv'

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11.9
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
 
    - name: Run training task
      run: |
        python src/steps/train.py
    
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: 'feat: update model after training workflow'
        branch: test
